/**
 * RFC 7807 problem-details document, extended with a project-specific
 * `code` field and an optional correlation id.
 *
 * See `docs/conventions/API-CONVENTIONS.md` for the error-code catalog.
 */
export interface ProblemDetails {
  /** A URI reference identifying the problem type. */
  type: string;
  /** Short, human-readable summary of the problem type. */
  title: string;
  /** HTTP status code generated by the origin server. */
  status: number;
  /** Human-readable explanation specific to this occurrence. */
  detail?: string;
  /** A URI reference identifying the specific occurrence. */
  instance?: string;
  /** Project-specific stable error code. */
  code: string;
  /** Correlation id propagated from `nestjs-cls` for tracing. */
  correlationId?: string;
  /** Optional structured details — e.g. validation field errors. */
  errors?: readonly Record<string, unknown>[];
}
