import { beforeAll, afterAll, describe, expect, it } from '@jest/globals';
import { Test } from '@nestjs/testing';
import {
  FastifyAdapter,
  type NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { DataSource } from 'typeorm';
import request from 'supertest';
import nock from 'nock';
import { randomUUID } from 'node:crypto';
import {
  recommendationResponseSchema,
  layerTraceResponseSchema,
} from '@innlab/contracts';
import { AppModule } from '../../../../src/app.module.js';
import { configureApp } from '../../../../src/shared/kernel/infrastructure/http/configure-app.js';
import { insertInitiativeWithProfile } from '../../support/initiative-rows.js';
import {
  authenticateAgainst,
  E2E_USER,
} from '../../support/authenticated-app.js';
import { agroconectaAnswers } from '../../support/agroconecta-case.js';

/**
 * E2E — full portfolio routing run for AgroConecta.
 *
 * Needs the real database, migrated and seeded:
 *   pnpm --filter @innlab/api db:migration:run && db:seed
 *
 * Follows the pattern of the other e2e suites (real `AppModule` +
 * supertest against the configured database), not Testcontainers.
 *
 * The 48 answers are chosen to produce exactly the profile of the case.
 * With 8 answers per dimension and the SA-06 conversion table:
 *
 *   TRL  sum 26 → 3.250 → IRL 6      IPRL sum  9 → 1.125 → IRL 1
 *   CRL  sum 19 → 2.375 → IRL 4      TmRL sum 22 → 2.750 → IRL 5
 *   BRL  sum 15 → 1.875 → IRL 3      FRL  sum 13 → 1.625 → IRL 2
 */

describe('Enrutamiento de portafolio (e2e) — AgroConecta', () => {
  let app: NestFastifyApplication;
  let dataSource: DataSource;
  let diagnosticId: string;
  let initiativeId: string;
  // Agent with the Authorization header by default: the global guard
  // rejects any request without a token.
  let agent: ReturnType<typeof request.agent>;

  beforeAll(async () => {
    const moduleFixture = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    // Same adapter and same pipeline as `main.ts`, so the suite runs the
    // pipeline that gets deployed.
    app = moduleFixture.createNestApplication<NestFastifyApplication>(
      new FastifyAdapter({ logger: false }),
    );
    configureApp(app);
    await app.init();
    await app.getHttpAdapter().getInstance().ready();

    agent = request
      .agent(app.getHttpServer())
      .set('Authorization', authenticateAgainst(app));

    dataSource = app.get(DataSource);
    diagnosticId = randomUUID();

    // ── Diagnostic and initiative characterization ─────────────────────
    //
    // Inserted directly: this suite tests the routing, not the consent and
    // initiative flow, which `initiative/registration-flow` covers.
    await dataSource.query(
      `INSERT INTO irl_diagnostic.diagnostic
         (id, cognito_user_id, state, id_framework_version)
       VALUES ($1, $2, 'QUESTIONNAIRE_IN_PROGRESS', (SELECT id FROM irl_catalog.framework_version WHERE code = 'KTH-IRL-1.0'))`,
      [diagnosticId, E2E_USER.sub],
    );

    initiativeId = await insertInitiativeWithProfile(
      dataSource,
      diagnosticId,
      E2E_USER.sub,
    );

    // ── Questionnaire + maturity profile ──────────────────────────────
    const statements = await dataSource.query<
      { id_statement: string; code: string; sequence: number }[]
    >(
      `SELECT a.id_statement, d.code, a.sequence
         FROM irl_catalog.statement a
         JOIN irl_catalog.dimension d ON d.id_dimension = a.id_dimension
        ORDER BY d.sequence, a.sequence`,
    );

    const answers = agroconectaAnswers(statements);

    await agent
      .post(`/api/v1/diagnostics/${diagnosticId}/finalize-initial`)
      .send({ answers })
      .expect(201);
  }, 60_000);

  afterAll(async () => {
    if (dataSource?.isInitialized) {
      await dataSource.query(
        `DELETE FROM irl_diagnostic.diagnostic WHERE id = $1`,
        [diagnosticId],
      );
      await dataSource.query(
        `DELETE FROM irl_diagnostic.initiative WHERE id = $1`,
        [initiativeId],
      );
    }
    nock.cleanAll();
    await app?.close();
  });

  it('el perfil de partida es el de AgroConecta', async () => {
    const res = await agent
      .get(`/api/v1/diagnostics/${diagnosticId}/profile`)
      .expect(200);

    const profile = res.body as {
      dimensionResults: { dimensionCode: string; irlLevel: number }[];
    };
    const levels = Object.fromEntries(
      profile.dimensionResults.map((r) => [r.dimensionCode, r.irlLevel]),
    );
    expect(levels).toEqual({
      TRL: 6,
      CRL: 4,
      BRL: 3,
      IPRL: 1,
      TmRL: 5,
      FRL: 2,
    });
  });

  it('aceptar el análisis profundo recomienda Reto Express, con Academia a la Medida como alternativa', async () => {
    // The recommendation is no longer generated by its own POST: `routing/`
    // calculates it when it reacts to the acceptance of the deep analysis.
    await agent
      .post(`/api/v1/diagnostics/${diagnosticId}/deep-analysis`)
      .expect(201);

    const res = await agent
      .get(`/api/v1/diagnostics/${diagnosticId}/recommendation`)
      .expect(200);

    const dto = recommendationResponseSchema.parse(res.body);

    expect(dto.resultType).toBe('RECOMMENDATION');
    expect(dto.primary?.name).toBe('Reto Express');
    expect(dto.primary?.score).toBeCloseTo(3.3, 3);
    expect(dto.primary?.adjustmentReason).toBeNull();
    // INC-02 put Academia a la Medida in position 2. It has no score and is
    // exempt from the threshold; every scored service after it is below 2.5.
    expect(dto.alternatives.map((a) => [a.name, a.position, a.score])).toEqual([
      ['Academia a la Medida', 2, null],
    ]);
    expect(dto.alternatives[0].adjustmentReason).toContain(
      'brechas en tres o más dimensiones',
    );
  });

  it('cada servicio trae la descripción del catálogo del portafolio', async () => {
    const res = await agent
      .get(`/api/v1/diagnostics/${diagnosticId}/recommendation`)
      .expect(200);
    const dto = recommendationResponseSchema.parse(res.body);

    expect(dto.primary?.description).toContain('formato intensivo');
    expect(dto.alternatives[0].description).toContain('aprendizaje basado en proyectos');
  });

  it('la justificación habla de afinidad global: ningún servicio atiende IPRL, el cuello de botella', () => {
    return agent
      .get(`/api/v1/diagnostics/${diagnosticId}/recommendation`)
      .expect(200)
      .expect((res) => {
        const dto = recommendationResponseSchema.parse(res.body);
        expect(dto.justification).toBe(
          'Reto Express es el servicio con mayor afinidad global con el perfil de la iniciativa.',
        );
      });
  });

  it('GET /recommendation/trace expone las tres capas y el servicio que INC-02 metió en el ranking', async () => {
    const res = await agent
      .get(`/api/v1/diagnostics/${diagnosticId}/recommendation/trace`)
      .expect(200);

    const trace = layerTraceResponseSchema.parse(res.body);

    // Layer 1 — no confirmed link with the university.
    expect(trace.layer1Excluded.map((e) => [e.ruleCode, e.name])).toEqual([
      ['ELG-01A', 'Célula de Grado · Pregrado'],
      ['ELG-01B', 'Célula de Grado · Posgrado'],
    ]);

    // Layer 2 — only scored services; adjustment-only ones never appear.
    expect(trace.rankingBeforeExceptions.map((r) => [r.name, r.score])).toEqual(
      [
        ['Reto Express', 3.3],
        ['Célula Dedicada · Co.LAB', 2.15],
        ['Consultoría Experta', 2],
        ['Reto en el Aula', 1.8],
        ['Semillero con Propósito', 1.45],
        ['Talento In-House', 0.9],
      ],
    );

    // Layer 3 — INC-02 puts Academia a la Medida into position 2, without a score.
    expect(trace.appliedExceptions.map((e) => [e.code, e.action])).toEqual([
      ['INC-02', 'INCLUDE'],
    ]);
    expect(trace.appliedExceptions[0].effect).toBe(
      'Academia a la Medida entra al ranking en el puesto 2, sin puntaje',
    );
    expect(trace.discardedExceptions.map((e) => e.code)).toEqual([
      'E-02',
      'E-03',
      'INC-01',
      'INC-03',
      'INC-04',
    ]);
    expect(
      trace.rankingAfterExceptions.map((r) => [
        r.position,
        r.name,
        r.score,
        r.includedBy?.ruleCode ?? null,
      ]),
    ).toEqual([
      [1, 'Reto Express', 3.3, null],
      [2, 'Academia a la Medida', null, 'INC-02'],
      [3, 'Célula Dedicada · Co.LAB', 2.15, null],
      [4, 'Consultoría Experta', 2, null],
      [5, 'Reto en el Aula', 1.8, null],
      [6, 'Semillero con Propósito', 1.45, null],
      [7, 'Talento In-House', 0.9, null],
    ]);
    // The calculated winner is still first: the result is not the adjustment's.
    expect(trace.adjustedByException).toBe(false);

    // The characterization is complete in this case, so there is no
    // silent degradation to record.
    expect(trace.incompleteCharacterization).toEqual([]);

    expect(trace.factsHash).toHaveLength(64);
  });

  it('volver a aceptar el análisis profundo es idempotente y no acumula filas', async () => {
    await agent
      .post(`/api/v1/diagnostics/${diagnosticId}/deep-analysis`)
      .expect(201);

    const [{ count }] = await dataSource.query<{ count: string }[]>(
      `SELECT COUNT(*)::text AS count
         FROM irl_diagnostic.portfolio_recommendation
        WHERE id_diagnostic = $1`,
      [diagnosticId],
    );
    expect(count).toBe('1');
  });

  it("answers another user's diagnostic as missing (404), not revealing it exists", async () => {
    const other = randomUUID();
    await dataSource.query(
      `INSERT INTO irl_diagnostic.diagnostic
         (id, cognito_user_id, state, id_framework_version)
       VALUES ($1, 'another-user', 'QUESTIONNAIRE_IN_PROGRESS', (SELECT id FROM irl_catalog.framework_version WHERE code = 'KTH-IRL-1.0'))`,
      [other],
    );

    try {
      const res = await agent
        .get(`/api/v1/diagnostics/${other}/recommendation`)
        .expect(404);
      expect((res.body as { code: string }).code).toBe('NOT_FOUND');
    } finally {
      await dataSource.query(
        `DELETE FROM irl_diagnostic.diagnostic WHERE id = $1`,
        [other],
      );
    }
  });

  it('un diagnóstico sin recomendación generada devuelve 409, no 404', async () => {
    const other = randomUUID();
    await dataSource.query(
      `INSERT INTO irl_diagnostic.diagnostic
         (id, cognito_user_id, state, id_framework_version)
       VALUES ($1, $2, 'QUESTIONNAIRE_IN_PROGRESS', (SELECT id FROM irl_catalog.framework_version WHERE code = 'KTH-IRL-1.0'))`,
      [other, E2E_USER.sub],
    );

    try {
      const res = await agent
        .get(`/api/v1/diagnostics/${other}/recommendation`)
        .expect(409);
      expect((res.body as { code: string }).code).toBe(
        'ROUTING_RECOMMENDATION_NOT_GENERATED',
      );
    } finally {
      await dataSource.query(
        `DELETE FROM irl_diagnostic.diagnostic WHERE id = $1`,
        [other],
      );
    }
  });
});
