import { describe, expect, it } from '@jest/globals';
import fc from 'fast-check';
import { DIMENSION_CODES, type DimensionCode } from '@innlab/contracts';
import { DependencyGraph } from '../../../../../src/modules/roadmap/domain/value-objects/dependency-graph.vo.js';
import { RoadmapClosureService } from '../../../../../src/modules/roadmap/domain/services/roadmap-closure.service.js';
import { TopologicalLayeringService } from '../../../../../src/modules/roadmap/domain/services/topological-layering.service.js';
import { TargetLevelCalculatorService } from '../../../../../src/modules/roadmap/domain/services/target-level-calculator.service.js';

/**
 * Properties of the engine over arbitrary graphs and profiles.
 *
 * DAGs are generated by construction, not by rejection: the canonical
 * order of `DIMENSION_CODES` is fixed as the topological order and only
 * edges from a lower index to a higher one are allowed. That way any
 * subset of those edges is acyclic and the generator discards no case,
 * which is what would make an `fc.pre()` slow and irregular.
 */
const closureService = new RoadmapClosureService();
const layeringService = new TopologicalLayeringService();
const targetService = new TargetLevelCalculatorService();

const ACYCLIC_PAIRS: [DimensionCode, DimensionCode][] = [];
for (let i = 0; i < DIMENSION_CODES.length; i += 1) {
  for (let j = i + 1; j < DIMENSION_CODES.length; j += 1) {
    ACYCLIC_PAIRS.push([DIMENSION_CODES[i], DIMENSION_CODES[j]]);
  }
}

const arbGraph = fc
  .tuple(
    fc.subarray(ACYCLIC_PAIRS),
    fc.array(fc.integer({ min: 1, max: 9 }), {
      minLength: ACYCLIC_PAIRS.length,
      maxLength: ACYCLIC_PAIRS.length,
    }),
    fc.array(fc.integer({ min: 1, max: 9 }), { minLength: 6, maxLength: 6 }),
  )
  .map(([pairs, reqs, mins]) =>
    DependencyGraph.create(
      pairs.map(([source, target], i) => ({
        source,
        target,
        minimumRequiredLevel: reqs[i % reqs.length],
      })),
      DIMENSION_CODES.map((d, i) => ({
        dimension: d,
        minimumExpectedLevel: mins[i],
      })),
    ),
  );

const arbProfile = fc
  .array(fc.integer({ min: 1, max: 9 }), { minLength: 6, maxLength: 6 })
  .map(
    (ns) =>
      new Map<DimensionCode, number>(
        DIMENSION_CODES.map((d, i) => [d, ns[i]]),
      ),
  );

describe('Propiedades del motor de roadmap', () => {
  it('ninguna dimensión aparece en una layer anterior a la de un predecesor suyo', () => {
    // This is the property that defines a correct topological order: if u
    // enables v and both are intervened, u cannot come later.
    fc.assert(
      fc.property(arbGraph, arbProfile, (graph, levels) => {
        const closure = closureService.compute(levels, graph);
        const layers = layeringService.layer(closure, graph);

        const layerOf = new Map<DimensionCode, number>();
        layers.forEach((layer, i) => layer.forEach((d) => layerOf.set(d, i)));

        for (const e of graph.allEdges()) {
          if (!closure.has(e.source) || !closure.has(e.target)) continue;
          expect(layerOf.get(e.source)!).toBeLessThan(layerOf.get(e.target)!);
        }
      }),
      { numRuns: 300 },
    );
  });

  it('toda dimensión intervenida tiene una meta estrictamente mayor que su nivel', () => {
    // If this were violated, there would be a phase with nothing to do,
    // a sign that the closure took in a dimension that did not need it.
    fc.assert(
      fc.property(arbGraph, arbProfile, (graph, levels) => {
        const closure = closureService.compute(levels, graph);
        const targets = targetService.compute(closure, graph);

        for (const d of closure) {
          expect(targets.get(d)!).toBeGreaterThan(levels.get(d)!);
        }
      }),
      { numRuns: 300 },
    );
  });

  it('las layers son una partición exacta del conjunto a intervenir', () => {
    fc.assert(
      fc.property(arbGraph, arbProfile, (graph, levels) => {
        const closure = closureService.compute(levels, graph);
        const layers = layeringService.layer(closure, graph);
        const flattened = layers.flat();

        expect(flattened).toHaveLength(closure.size);
        expect(new Set(flattened).size).toBe(closure.size);
        for (const d of flattened) expect(closure.has(d)).toBe(true);
      }),
      { numRuns: 300 },
    );
  });

  it('el cierre contiene siempre al focus', () => {
    fc.assert(
      fc.property(arbGraph, arbProfile, (graph, levels) => {
        const closure = closureService.compute(levels, graph);
        for (const d of DIMENSION_CODES) {
          if (levels.get(d)! < graph.expectedMinimum(d)) {
            expect(closure.has(d)).toBe(true);
          }
        }
      }),
      { numRuns: 300 },
    );
  });

  it('el motor es determinista', () => {
    fc.assert(
      fc.property(arbGraph, arbProfile, (graph, levels) => {
        const a = layeringService.layer(closureService.compute(levels, graph), graph);
        const b = layeringService.layer(closureService.compute(levels, graph), graph);
        expect(a).toEqual(b);
      }),
      { numRuns: 200 },
    );
  });
});
