import { z } from 'zod';

/**
 * Universally unique identifier (UUID v4 generated by the application).
 *
 * Every primary key of an aggregate is a UUID generated in code before
 * persisting, not by the database, so domain entities can be built without
 * a round trip.
 *
 * Centralized here so every schema reuses the same validator instead of an
 * inline `z.string().uuid()` — a single source for the error message and
 * the format.
 */
export const uuidSchema = z.string().uuid().describe('UUID v4');

export type Uuid = z.infer<typeof uuidSchema>;
