import { randomUUID } from 'node:crypto';
import { InvariantViolationError } from '../errors/invariant-violation.error.js';

/**
 * Universally Unique Identifier value object — wraps a string so the
 * type system can distinguish a "raw string id" from a known-good UUID.
 *
 * UUIDs are generated by the application (per PROJECT-SUMMARY.md §1.8:
 * "UUID primary keys generated by the application, not by Postgres, so
 * domain entities can construct themselves without a roundtrip").
 *
 * `node:crypto.randomUUID()` produces a RFC-4122 v4 identifier, which
 * matches the regex validation here.
 */
const UUID_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export class Uuid {
  private constructor(public readonly value: string) {}

  static create(input: string): Uuid {
    if (!UUID_REGEX.test(input)) {
      throw new InvariantViolationError(`Invalid UUID format: '${input}'`, {
        received: input,
      });
    }
    return new Uuid(input);
  }

  static generate(): Uuid {
    return new Uuid(randomUUID());
  }

  equals(other: Uuid): boolean {
    return this.value === other.value;
  }

  toString(): string {
    return this.value;
  }
}
